In [20]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/ct-data-2017/hmda_2017_ct_all-records_labels.csv

In [21]:
ct_data = pd.read_csv("/kaggle/input/ct-data-2017/hmda_2017_ct_all-records_labels.csv")
print(f"{ct_data.head(5)}")

   as_of_year respondent_id                                  agency_name  \
0        2017       2888798                       Federal Reserve System
1        2017          8663        Federal Deposit Insurance Corporation
2        2017    26-4599244  Department of Housing and Urban Development
3        2017    26-2261031  Department of Housing and Urban Development
4        2017    26-2261031  Department of Housing and Urban Development

  agency_abbr  agency_code loan_type_name  loan_type  \
0         FRS            2    FHA-insured          2
1        FDIC            3   Conventional          1
2         HUD            7   Conventional          1
3         HUD            7   Conventional          1
4         HUD            7   Conventional          1

                                  property_type_name  property_type  \
0  One-to-four family dwelling (other than manufa...              1
1  One-to-four family dwelling (other than manufa...              1
2  One-to-four family dwelling (other than manufa...              1
3  One-to-four family dwelling (other than manufa...              1
4  One-to-four family dwelling (other than manufa...              1

  loan_purpose_name  ...  county_code applicant_race_name_1  applicant_race_1  \
0     Home purchase  ...            9                 White                 5
1       Refinancing  ...            9                 White                 5
2     Home purchase  ...            9                 White                 5
3       Refinancing  ...            9                 White                 5
4       Refinancing  ...            9                 White                 5

   co_applicant_race_name_1 co_applicant_race_1  applicant_sex_name  \
0           No co-applicant                   8              Female
1                     White                   5                Male
2           No co-applicant                   8              Female
3                     White                   5                Male
4           No co-applicant                   8                Male

  applicant_sex  co_applicant_sex_name co_applicant_sex applicant_income_000s
0             2        No co-applicant                5                  74.0
1             1                   Male                1                 252.0
2             2        No co-applicant                5                  66.0
3             1                 Female                2                 183.0
4             1        No co-applicant                5                  81.0

[5 rows x 31 columns]

In [22]:
ct_data.describe()

,as_of_year,agency_code,loan_type,property_type,loan_purpose,owner_occupancy,loan_amount_000s,preapproval,action_taken,county_code,applicant_race_1,co_applicant_race_1,applicant_sex,co_applicant_sex,applicant_income_000s
count,88649.0,88649.000000,88649.000000,88649.000000,88649.000000,88649.000000,88649.000000,88649.000000,88649.000000,88649.000000,88649.000000,88649.00000,88649.000000,88649.000000,88558.000000
mean,2017.0,6.788424,1.302790,1.006204,1.796377,1.065460,262.610689,2.792485,0.812045,5.683144,4.906948,6.71042,1.550655,3.682027,129.917399
std,0.0,2.119500,0.601082,0.090658,0.933546,0.252796,361.498966,0.455721,0.390678,4.379323,0.963269,1.59811,0.754037,1.577106,201.333690
min,2017.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000
25%,2017.0,7.000000,1.000000,1.000000,1.000000,1.000000,130.000000,3.000000,1.000000,1.000000,5.000000,5.00000,1.000000,2.000000,60.000000
50%,2017.0,7.000000,1.000000,1.000000,1.000000,1.000000,200.000000,3.000000,1.000000,3.000000,5.000000,8.00000,1.000000,5.000000,89.000000
75%,2017.0,9.000000,1.000000,1.000000,3.000000,1.000000,300.000000,3.000000,1.000000,9.000000,5.000000,8.00000,2.000000,5.000000,143.000000
max,2017.0,9.000000,4.000000,3.000000,3.000000,3.000000,39000.000000,3.000000,1.000000,15.000000,7.000000,8.00000,4.000000,5.000000,10562.000000

In [23]:
ct_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88649 entries, 0 to 88648
Data columns (total 31 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   as_of_year                88649 non-null  int64
 1   respondent_id             88649 non-null  object
 2   agency_name               88649 non-null  object
 3   agency_abbr               88649 non-null  object
 4   agency_code               88649 non-null  int64
 5   loan_type_name            88649 non-null  object
 6   loan_type                 88649 non-null  int64
 7   property_type_name        88649 non-null  object
 8   property_type             88649 non-null  int64
 9   loan_purpose_name         88649 non-null  object
 10  loan_purpose              88649 non-null  int64
 11  owner_occupancy_name      88649 non-null  object
 12  owner_occupancy           88649 non-null  int64
 13  loan_amount_000s          88649 non-null  int64
 14  preapproval_name          88649 non-null  object
 15  preapproval               88649 non-null  int64
 16  action_taken_name         88649 non-null  object
 17  action_taken              88649 non-null  int64
 18  msamd_name                88647 non-null  object
 19  state_abbr                88649 non-null  object
 20  county_name               88649 non-null  object
 21  county_code               88649 non-null  int64
 22  applicant_race_name_1     88649 non-null  object
 23  applicant_race_1          88649 non-null  int64
 24  co_applicant_race_name_1  88649 non-null  object
 25  co_applicant_race_1       88649 non-null  int64
 26  applicant_sex_name        88649 non-null  object
 27  applicant_sex             88649 non-null  int64
 28  co_applicant_sex_name     88649 non-null  object
 29  co_applicant_sex          88649 non-null  int64
 30  applicant_income_000s     88558 non-null  float64
dtypes: float64(1), int64(14), object(16)
memory usage: 21.0+ MB

In [24]:
# one_hot_encoded_training_predictors = pd.get_dummies(ct_data)

In [25]:
# one_hot_encoded_training_predictors.info()

In [26]:
loan_amount = ct_data["loan_amount_000s"].values
loan_amount = loan_amount.reshape(-1, 1)
app_income = ct_data["applicant_income_000s"].values
app_income = app_income.reshape(-1,1)
location = ct_data["county_name"].values
location = location.reshape(-1,1)
action = ct_data["action_taken"].values

In [27]:
loan_amount_train, loan_amount_test, action_train, action_test = train_test_split(loan_amount, action, train_size=0.8, test_size=0.2, random_state=100)
app_income_train, app_income_test, actionapp_income_train, actionapp_income_test = train_test_split(app_income, action, train_size=0.8, test_size=0.2, random_state=100)

lm1 = LinearRegression()
lm1.fit(loan_amount_train,action_train)
loan_amount_action_predict = lm1.predict(loan_amount_test)

lm2 = LinearRegression()
lm2.fit(app_income_train,actionapp_income_train)
app_incomeaction_predict = lm2.predict(app_income_test)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').